### ISSUE TITLE
1关于从为知笔记导入html文件到anki的问题

### ISSUE THREAD

**Issue by yanyu2015** [tansongchen/Evernote2Anki#4]
1 以html文件导入为知笔记到anki时，图片并没有被成功导入（图片是以粘贴的形式贴入笔记的本地图片），同目录下是有同名的_files 文件夹的，鉴于原作者是在ios端开发，可能是因为windows下的盘符是"\"的原因。
2 相关测试文件已经上传
[测试文件.zip](https://github.com/tansongchen/Evernote2Anki/files/3931886/default.zip)

**Comment by tansongchen** [comment]
这个测试文件我导入的时候好像没有遇到任何问题……

![image](https://user-images.githubusercontent.com/31927845/70587636-4a536f80-1b7f-11ea-930e-b1652beefc94.png)

文件管理是用的 Python 的 os.path 模块，理论上来说应该是跨平台的，我在程序中也没有显式地出现正斜杠还是反斜杠。我现在手头没有 Windows 的电脑，等回头有时间在 Windows 上测试一下。

另外，公式使用 Markdown 里的 $$...$$ 语法编写体验会更好😄️

**Comment by yanyu2015** [comment]
> 这个测试文件我导入的时候好像没有遇到任何问题……
> 
> ![image](https://user-images.githubusercontent.com/31927845/70587636-4a536f80-1b7f-11ea-930e-b1652beefc94.png)
> 
> 文件管理是用的 Python 的 os.path 模块，理论上来说应该是跨平台的，我在程序中也没有显式地出现正斜杠还是反斜杠。我现在手头没有 Windows 的电脑，等回头有时间在 Windows 上测试一下。
> 
> 另外，公式使用 Markdown 里的 $$...$$ 语法编写体验会更好

我这边显示的情况是这样的
![image](https://user-images.githubusercontent.com/11142054/70624411-2a917980-1c5b-11ea-8db2-9e47e38d7ba2.png)

既然有图标但没有图片，一般猜测都是路径不对吧？会不会是解析的时候呢？
